# Generated by Django 4.2.6 on 2023-11-27 07:59

from django.db import migrations, models
import pevsearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('pevsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=pevsearch.models.LongURLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(),
        ),
    ]
