# Generated by Django 4.2.6 on 2024-05-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pevsearch', '0006_alter_tag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
